name: .NET Core

on: 
 push:
  branches: 
    - master
jobs:
  test:
    name: Testing  
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use .NET 3.1.301
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build MathCore.WPF.Styles.csproj
      run: dotnet build MathCore.WPF.Styles/MathCore.WPF.Styles.csproj -c Release --no-restore 
    - name: Build MathCore.WPF.Style.Tests.csproj
      run: dotnet build Tests/MathCore.WPF.Style.Tests/MathCore.WPF.Style.Tests.csproj -c Release --no-restore
    - name: Run Test
      run: dotnet test Tests/MathCore.WPF.Style.Tests/MathCore.WPF.Style.Tests.csproj  --no-restore --verbosity normal
    - name: Packing
      run: dotnet pack Tests/MathCore.WPF.Style.Tests/MathCore.WPF.Style.Tests.csproj  --no-build -c Release -v q
    - name: Publishing
      run: dotnet nuget push MathCore.WPF.Style/bin/Release/*.nupkg -s http://api.nuget.org/v3/index.json -n --skip-duplicate -k ${{secret.NuGet_apiKey}}

      
